# Generated by Django 5.0.7 on 2024-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=15, unique=True)),
                ("is_spam", models.BooleanField(default=False)),
                ("owner_name", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
