# Generated by Django 5.0.7 on 2024-07-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Calls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="phone_images/"),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="owner_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
